// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DataEntry struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Views     int    `json:"views"`
	Timestamp string `json:"timestamp"`
}

type InputDataEntry struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Views     int    `json:"views"`
	Timestamp string `json:"timestamp"`
}
